publish_voxel_map: false #was false
transform_tolerance: 0.5
meter_scoring: true


obstacle_range: 9.0 #to verify
raytrace_range: 9.9 #to verify

footprint: [[0.225, -0.24], 
            [-0.225, -0.24], 
            [-0.225, 0.24], 
            [0.225, 0.24]]
#robot_radius: 0.33 #was 0.33
#footprint_padding: 0.02 #was 0.0