global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 #was 5.0
  publish_frequency: 2.0
  #always_send_full_costmap: false #default is false
  rolling_window: false
  resolution: 0.05 #was 0.05
  width: 30 #was 30
  height: 30 #was 30
  origin_x: -15 #was -15
  origin_y: -15 #was -15