local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  #to verify
  update_frequency: 5.0 #was 5.0
  publish_frequency: 10.0 #was 10.0
  static_map: false
  rolling_window: true
  width: 6.0 #was 6.0
  height: 6.0 #was 6.0
  resolution: 0.03 #was 0.05